<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sdjulgerova" name="com.sirma.itt.javacourse.collections.ExceptionManagerTest" tests="5" failures="0" timestamp="10 May 2013 10:59:33 GMT" time="0.031" errors="0">
  <testcase name="testAddExceptionMessage" time="0.000" classname="com.sirma.itt.javacourse.collections.ExceptionManagerTest"/>
  <testcase name="testAddExceptionMessageUsingCode" time="0.015" classname="com.sirma.itt.javacourse.collections.ExceptionManagerTest"/>
  <testcase name="testAddExceptionMessageUsingCode" time="0.000" classname="com.sirma.itt.javacourse.collections.ExceptionManagerTest"/>
  <testcase name="testGetMessages" time="0.000" classname="com.sirma.itt.javacourse.collections.ExceptionManagerTest"/>
  <testcase name="testAddExceptionMessage" time="0.016" classname="com.sirma.itt.javacourse.collections.ExceptionManagerTest"/>
</testsuite> <!-- com.sirma.itt.javacourse.collections.ExceptionManagerTest -->
