<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38478" started-at="2013-06-02T04:57:08Z" finished-at="2013-06-02T04:57:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38478" started-at="2013-06-02T04:57:08Z" finished-at="2013-06-02T04:57:47Z">
      <class name="com.sirma.itt.javacourse.io.ConsoleReaderTest">
        <test-method status="PASS" signature="testReadFloat(float)[pri:0, instance:com.sirma.itt.javacourse.io.ConsoleReaderTest@1090c56]" name="testReadFloat" duration-ms="10362" started-at="2013-06-01T21:57:08Z" data-provider="validFloatData" finished-at="2013-06-01T21:57:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[8.56]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReadFloat -->
        <test-method status="PASS" signature="testReadInt(int)[pri:0, instance:com.sirma.itt.javacourse.io.ConsoleReaderTest@1090c56]" name="testReadInt" duration-ms="4583" started-at="2013-06-01T21:57:19Z" data-provider="validIntData" finished-at="2013-06-01T21:57:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReadInt -->
        <test-method status="PASS" signature="testReadString(java.lang.String)[pri:0, instance:com.sirma.itt.javacourse.io.ConsoleReaderTest@1090c56]" name="testReadString" duration-ms="3783" started-at="2013-06-01T21:57:23Z" data-provider="validStringData" finished-at="2013-06-01T21:57:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReadString -->
        <test-method status="FAIL" signature="validate(char)[pri:0, instance:com.sirma.itt.javacourse.io.ConsoleReaderTest@1090c56]" name="validate" duration-ms="19703" started-at="2013-06-01T21:57:27Z" data-provider="validCharData" finished-at="2013-06-01T21:57:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[a]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [a] but found [c]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [a] but found [c]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:328)
	at org.testng.Assert.assertEquals(Assert.java:338)
	at com.sirma.itt.javacourse.io.ConsoleReaderTest.validate(ConsoleReaderTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate -->
      </class> <!-- com.sirma.itt.javacourse.io.ConsoleReaderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
